"""2026-08-25 중복 글을 7월 21일 글의 심화 후속편으로 한 번만 교체한다."""
import asyncio
import json
import re
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[1] / ".env")

from blog_generator import (  # noqa: E402
    _generate_thumbnail,
    _logged_create,
    generate_comments,
    generate_scene_prompt_from_content,
    notify_search_engines_bg,
    record_post_costs,
    revalidate_frontend_bg,
)
from db.connection import SessionLocal  # noqa: E402
from db.models import BlogComment, BlogPost  # noqa: E402


SLUG = "discovery-2026-08-25"
PREVIOUS_URL = "https://cosmic-hustle.ai.kr/discovery-2026-07-21"


def parse_json(text: str) -> dict:
    start, end = text.find("{"), text.rfind("}")
    if start < 0 or end < start:
        raise RuntimeError("수정 결과에 JSON이 없음")
    return json.loads(text[start:end + 1])


async def main() -> None:
    db = SessionLocal()
    try:
        post = db.query(BlogPost).filter(BlogPost.slug == SLUG).first()
        if not post:
            raise RuntimeError(f"수정 대상 없음: {SLUG}")
        if "지하에 둬도 끝이 아니다" in post.title:
            print(f"이미 수정 완료: {SLUG}")
            return

        costs: list[dict] = []
        client = anthropic.AsyncAnthropic()
        prompt = f"""아래 포케 대리의 과학 블로그 글을 완전히 다시 편집하라.

현재 글은 7월 21일 글과 '우주 입자→큐비트 오류→지하 설치'라는 설명이 겹친다. 새 글은 반드시 전편을 짧게 연결한 뒤, **지하 설치만으로 끝나지 않는 상관 오류와 칩 수준의 대응**을 중심으로 쓴 심화 후속편이어야 한다.

전편 링크: {PREVIOUS_URL}

검증된 1차 자료:
1. Nature Communications (2025), Cosmic-ray-induced correlated errors in superconducting qubit array
https://www.nature.com/articles/s41467-025-59778-z
- 63큐비트 프로세서에서 뮤온·감마선이 준입자 폭주와 다중 큐비트 상관 오류를 일으키는 현상을 직접 관측.
- 준입자 포획과 재결합 특성이 오류 지속시간 완화에 중요.
2. Nature Communications (2025), Synchronous detection of cosmic rays and correlated errors in superconducting qubit arrays
https://www.nature.com/articles/s41467-025-61385-x
- 10개 트랜스몬 큐비트에서 우주선이 상관 오류 사건의 17.1±1.3%를 차지.
- 초전도 갭 엔지니어링이 영향을 줄이고 깊은 지하 시설 의존을 낮출 가능성.
3. npj Quantum Information (2021), Saving superconducting quantum processors from decay and correlated errors generated by gamma and cosmic rays
https://www.nature.com/articles/s41534-021-00431-0
- 오류 정정은 오류가 작고 서로 독립적이라는 조건에 기대므로 넓게 동시에 번지는 오류가 특히 위험.
- 정상 금속 또는 낮은 갭 초전도체 막으로 포논 에너지를 큐비트 밖으로 흘리는 설계를 제안.
4. Nature Communications (2022), Phonon downconversion to suppress correlated errors in superconducting qubits
https://www.nature.com/articles/s41467-022-33997-0
- 포논 다운컨버전으로 상관 오류를 억제하는 칩 설계 접근을 실험.

작성 규칙:
- 한국어 5,000~7,000자, 비전문가도 읽을 수 있게 포케의 호기심 많고 위트 있는 말투.
- 제목은 정확히 "양자컴퓨터를 지하에 둬도 끝이 아니다 — 우주방사선 동시 오류를 막는 방법".
- 첫 부분에서 전편과 링크를 명시하고, 전편의 '왜 지하인가' 설명은 3문장 이내로만 요약.
- 5개의 ## 소제목. 중심 순서는 상관 오류가 위험한 이유 → 오류 정정의 맹점 → 지하의 한계 → 칩 설계 대응(포논 배출·준입자 포획·갭 엔지니어링) → 독자에게 남는 의미.
- 위 자료에 없는 숫자나 단정은 만들지 말 것. MIT만의 연구라고 잘못 쓰지 말 것.
- 본문 안에 위 Nature/npj 원문 링크를 자연스럽게 넣고, 맨 끝에 참고자료 목록을 둔다.
- 전편과 같은 소제목이나 결론을 재사용하지 말 것.
- 한자 어원 설명은 넣지 말 것.
- 마크다운 본문에 # 제목은 넣지 말고 ##부터 사용.

현재 본문(참고만 하고 구조와 문장은 재사용하지 말 것):
{post.content}

JSON만 출력:
{{"title":"...","summary":"150자 안팎","seo_title":"60자 안팎","seo_description":"160자 안팎","trending_topic":"Discovery: ...","tags":["..."],"content":"마크다운 본문"}}
"""
        message = await _logged_create(
            client,
            costs,
            "followup_rewrite",
            model="claude-sonnet-4-6",
            max_tokens=7000,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = "".join(block.text for block in message.content if block.type == "text")
        revised = parse_json(raw)
        content = revised.get("content", "")
        if len(content) < 5000 or len(re.findall(r"(?m)^## ", content)) != 5 or PREVIOUS_URL not in content:
            raise RuntimeError("수정 본문 검증 실패")

        scene = await generate_scene_prompt_from_content(
            post.agent_id, revised["title"], content, sink=costs
        )
        thumbnail_url = None
        for _ in range(3):
            thumbnail_url = await _generate_thumbnail(post.agent_id, scene, sink=costs)
            if thumbnail_url:
                break
        if not thumbnail_url:
            raise RuntimeError("새 썸네일 생성 실패 — 기존 글 유지")

        db.query(BlogComment).filter(BlogComment.post_id == post.id).delete()
        comments = await generate_comments(
            post.id, post.agent_id, revised["title"], content[:300]
        )
        for comment in comments:
            db.add(BlogComment(**comment))

        post.title = revised["title"]
        post.summary = revised["summary"]
        post.seo_title = revised["seo_title"]
        post.seo_description = revised["seo_description"]
        post.trending_topic = revised["trending_topic"]
        post.tags = json.dumps(revised["tags"], ensure_ascii=False)
        post.content = content
        post.thumbnail_url = thumbnail_url
        post.published = True
        record_post_costs(db, post.id, post.agent_id, costs)
        db.commit()

        notify_search_engines_bg(f"https://cosmic-hustle.ai.kr/{post.slug}")
        revalidate_frontend_bg([post.slug])
        print(f"후속편 교체 완료: {post.slug}")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    asyncio.run(main())
